### ISSUE TITLE
Compiling errors Apple Clang

### ISSUE THREAD

**Issue by cianciosa** [project-asgard/asgard#387]
**Describe the bug**
Asgard fails to compile using the Apple clang with 12.4.

#### First Bug ####
```
Scanning dependencies of target basis
[ 27%] Building CXX object CMakeFiles/basis.dir/src/basis.cpp.o
In file included from /Users/m4c/Projects/asgard/src/basis.cpp:2:
In file included from /Users/m4c/Projects/asgard/src/distribution.hpp:3:
/Users/m4c/Projects/asgard/src/elements.hpp:115:8: error: no template named 'unordered_map' in namespace 'std'; did you mean 'unordered_set'?
  std::unordered_map<int64_t, fk::vector<int>> id_to_coords_;
  ~~~~~^~~~~~~~~~~~~
       unordered_set
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/unordered_set:382:28: note: 'unordered_set' declared here
class _LIBCPP_TEMPLATE_VIS unordered_set
                           ^
In file included from /Users/m4c/Projects/asgard/src/basis.cpp:2:
In file included from /Users/m4c/Projects/asgard/src/distribution.hpp:3:
/Users/m4c/Projects/asgard/src/elements.hpp:75:26: error: no member named 'at' in 'std::__1::unordered_set<long long, fk::vector<int, mem_type::owner,
      resource::host>, std::__1::equal_to<long long>, std::__1::allocator<long long> >'
    return id_to_coords_.at(active_element_ids_[index]);
           ~~~~~~~~~~~~~ ^
2 errors generated.
make[2]: *** [CMakeFiles/basis.dir/src/basis.cpp.o] Error 1
make[1]: *** [CMakeFiles/basis.dir/all] Error 2
make: *** [all] Error 2
```
##### Fix #####
The line
https://github.com/project-asgard/asgard/blob/d43b3bdaf64db8385d5035f558acad7683ad59cf/src/elements.hpp#L10
Should be replaced with 
`#include <unordered_map>`

#### Second bug ####
```
Scanning dependencies of target adapt
[ 47%] Building CXX object CMakeFiles/adapt.dir/src/adapt.cpp.o
In file included from /Users/m4c/Projects/asgard/src/adapt.cpp:1:
In file included from /Users/m4c/Projects/asgard/src/adapt.hpp:2:
In file included from /Users/m4c/Projects/asgard/src/basis.hpp:2:
In file included from /Users/m4c/Projects/asgard/src/pde.hpp:6:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/map:708:17: error: no viable overloaded '='
        __ref() = __v.__get_value();
        ~~~~~~~ ^ ~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__tree:1691:39: note: in instantiation of member function
      'std::__1::__value_type<int, element_subgrid>::operator=' requested here
            __cache.__get()->__value_ = *__first;
                                      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__tree:1648:9: note: in instantiation of function template
      specialization 'std::__1::__tree<std::__1::__value_type<int, element_subgrid>, std::__1::__map_value_compare<int, std::__1::__value_type<int,
      element_subgrid>, std::__1::less<int>, true>, std::__1::allocator<std::__1::__value_type<int, element_subgrid> >
      >::__assign_multi<std::__1::__tree_const_iterator<std::__1::__value_type<int, element_subgrid>, std::__1::__tree_node<std::__1::__value_type<int,
      element_subgrid>, void *> *, long> >' requested here
        __assign_multi(__t.begin(), __t.end());
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/map:1014:21: note: in instantiation of member function
      'std::__1::__tree<std::__1::__value_type<int, element_subgrid>, std::__1::__map_value_compare<int, std::__1::__value_type<int, element_subgrid>,
      std::__1::less<int>, true>, std::__1::allocator<std::__1::__value_type<int, element_subgrid> > >::operator=' requested here
            __tree_ = __m.__tree_;
                    ^
/Users/m4c/Projects/asgard/src/adapt.cpp:315:23: note: in instantiation of member function 'std::__1::map<int, element_subgrid, std::__1::less<int>,
      std::__1::allocator<std::__1::pair<const int, element_subgrid> > >::operator=' requested here
  plan_               = new_plan;
                      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/utility:297:29: note: candidate function
      (the implicit copy assignment operator) not viable: no known conversion from 'const pair<const std::__1::__value_type<int, element_subgrid>::key_type,
      std::__1::__value_type<int, element_subgrid>::mapped_type>' to 'const pair<int &, element_subgrid &>' for 1st argument
struct _LIBCPP_TEMPLATE_VIS pair
                            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/utility:512:11: note: candidate function not viable: no
      known conversion from 'const std::__1::__value_type<int, element_subgrid>::value_type' (aka 'const pair<const int, element_subgrid>') to 'const typename
      conditional<is_copy_assignable<first_type>::value && is_copy_assignable<second_type>::value, pair<int &, element_subgrid &>, __nat>::type'
      (aka 'const std::__1::__nat') for 1st argument
    pair& operator=(typename conditional<
          ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/utility:525:11: note: candidate function not viable: no
      known conversion from 'const std::__1::__value_type<int, element_subgrid>::value_type' (aka 'const pair<const int, element_subgrid>') to 'typename
      conditional<is_move_assignable<first_type>::value && is_move_assignable<second_type>::value, pair<int &, element_subgrid &>, __nat>::type'
      (aka 'std::__1::__nat') for 1st argument
    pair& operator=(typename conditional<
          ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/utility:334:62: note: candidate template ignored: disabled
      by 'enable_if' [with _Tuple = const std::__1::pair<const int, element_subgrid> &]
    using _EnableB _LIBCPP_NODEBUG_TYPE = typename enable_if<_Val, bool>::type;
                                                             ^
1 error generated.
make[2]: *** [CMakeFiles/adapt.dir/src/adapt.cpp.o] Error 1
make[1]: *** [CMakeFiles/adapt.dir/all] Error 2
make: *** [all] Error 2
```

**To Reproduce**
1. git commit hash being built

d43b3bdaf64db8385d5035f558acad7683ad59cf

2. cmake command
```
 ASGARD_BLAS_PATH                 OFF                                                                                                                             
 ASGARD_BUILD_HDF5                OFF                                                                                                                             
 ASGARD_BUILD_OPENBLAS            OFF                                                                                                                             
 ASGARD_BUILD_PROFILE_DEPS        OFF                                                                                                                             
 ASGARD_BUILD_TESTS               ON                                                                                                                              
 ASGARD_GRAPHVIZ_PATH             OFF                                                                                                                             
 ASGARD_HDF5_PATH                 OFF                                                                                                                             
 ASGARD_IO_HIGHFIVE               OFF                                                                                                                             
 ASGARD_LAPACK_PATH               OFF                                                                                                                             
 ASGARD_PROFILE_GPERF_CPU         OFF                                                                                                                             
 ASGARD_PROFILE_GPERF_MEM         OFF                                                                                                                             
 ASGARD_PROFILE_GPROF             OFF                                                                                                                             
 ASGARD_PROFILE_PERF              OFF                                                                                                                             
 ASGARD_PROFILE_VALGRIND          OFF                                                                                                                             
 ASGARD_PROFILE_XRAY              OFF                                                                                                                             
 ASGARD_TESTING_RANKS             0                                                                                                                               
 ASGARD_USE_CUDA                  OFF                                                                                                                             
 ASGARD_USE_DOUBLE_PREC           ON                                                                                                                              
 ASGARD_USE_MPI                   ON                                                                                                                              
 ASGARD_USE_OPENMP                OFF                                                                                                                             
 ASGARD_USE_SLATE                 OFF                                                                                                                             
 BUILD_TESTING                    ON                                                                                                                              
 CMAKE_BUILD_TYPE                 Release                                                                                                                         
 CMAKE_EXECUTABLE_FORMAT          MACHO                                                                                                                           
 CMAKE_INSTALL_PREFIX             /usr/local                                                                                                                      
 CMAKE_OSX_ARCHITECTURES                                                                                                                                          
 CMAKE_OSX_DEPLOYMENT_TARGET      10.15                                                                                                                           
 CMAKE_OSX_SYSROOT                /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk                                  
 KRON_INCLUDE_DIR                 ~/Projects/asgard/contrib/kronmult     
```

3. full program/test invocation command
make

4. additional steps 
The second compiling error is not generated until the `<unordered_set> -> <unordered_map>` fix is made.

**Expected behavior**

**System:**
 - system name : Mark's iMac (macOS 10.15.7)
 - modules loaded : N/A
 - other systems where this is reproducible : TBD

**Additional context**

```
% clang --version
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by cianciosa** [comment]
The second issue is fixed in https://github.com/project-asgard/asgard/pull/398
